# These are a list of commands that will also work the same
# as /deluxepm (these all work, feel free to advertise which one you want players to use)
# - dpm
# - pmtoggle
# - dmtoggle
# - togglepms
# - togglepm
# - msgtoggle

plugin-prefix: "&b[&7DeluxePM&b]"

updater:
  check: true

messages:
  toggle: "/dpm"
  reload: "/deluxepm reload"
  help: "/dpm help"
  enabled: "PMs have been turned on"
  disabled: "PMs have been turned off"
  user-disabled: "This user has PMs turned off"
  reload-success: "Config has been successfully reloaded"

pm-commands:
- "/tell"
- "/whisper"
- "/r"
- "/msg"