name: DeluxePM
version: @version@
main: me.glaremasters.deluxepm.DeluxePM
authors: [blockslayer22]
description: Toggle PMs!

commands:
  deluxepm:
    description: Default help info
    aliases: [dpm, pmtoggle, dmtoggle, togglepms, togglepm, msgtoggle]

